controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_attributes:
    resource: 
        path: '../src/Bundle/'
        namespace: App\Bundle
    type: attribute